//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.07 at 01:16:45 PM EDT 
//


package org.dragon.yunpeng.project.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BOOKType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BOOKType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TITLE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="The Great Gatsby"/>
 *               &lt;enumeration value="To Kill a Mockingbird"/>
 *               &lt;enumeration value="1984"/>
 *               &lt;enumeration value="Pride and Prejudice"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AUTHOR">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="F. Scott Fitzgerald"/>
 *               &lt;enumeration value="Harper Lee"/>
 *               &lt;enumeration value="George Orwell"/>
 *               &lt;enumeration value="Jane Austen"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GENRE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Classic"/>
 *               &lt;enumeration value="Fiction"/>
 *               &lt;enumeration value="Dystopian"/>
 *               &lt;enumeration value="Romance"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LIBRARY_ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BOOKType", propOrder = {
    "id",
    "title",
    "author",
    "genre",
    "library_ID"
})
public class BOOK {

    @XmlElement(name = "ID")
    protected byte id;
    @XmlElement(name = "TITLE", required = true)
    protected String title;
    @XmlElement(name = "AUTHOR", required = true)
    protected String author;
    @XmlElement(name = "GENRE", required = true)
    protected String genre;
    @XmlElement(name = "LIBRARY_ID")
    protected byte library_ID;

    /**
     * Gets the value of the id property.
     * 
     */
    public byte getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(byte value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITLE() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITLE(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTHOR() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTHOR(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the genre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENRE() {
        return genre;
    }

    /**
     * Sets the value of the genre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENRE(String value) {
        this.genre = value;
    }

    /**
     * Gets the value of the library_ID property.
     * 
     */
    public byte getLIBRARY_ID() {
        return library_ID;
    }

    /**
     * Sets the value of the library_ID property.
     * 
     */
    public void setLIBRARY_ID(byte value) {
        this.library_ID = value;
    }

}
