//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.07 at 01:16:45 PM EDT 
//


package org.dragon.yunpeng.project.entities;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.dragon.yunpeng.project.entities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NewDataSet_QNAME = new QName("", "NewDataSet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.dragon.yunpeng.project.entities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link LIBRARY }
     * 
     */
    public LIBRARY createLIBRARY() {
        return new LIBRARY();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewDataSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NewDataSet")
    public JAXBElement<NewDataSet> createNewDataSet(NewDataSet value) {
        return new JAXBElement<NewDataSet>(_NewDataSet_QNAME, NewDataSet.class, null, value);
    }

}
